# -*- coding: utf-8 -*-
"""Password Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHdiPZ4wGK7nokHiAZnscF79rN7GuBPc
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ""

    for i in range(length):
        password += random.choice(characters)

    return password
def main():
    print("=== Python Password Generator ===")

    try:
        length = int(input("Enter the desired password length: "))

        if length <= 0:
            print("Password length must be greater than 0.")
            return

        password = generate_password(length)

        print("\nGenerated Password:")
        print(password)

    except ValueError:
        print("Please enter a valid number.")


if __name__ == "__main__":
    main()